FROM python:3

RUNE: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed. pip install --upgrade pip && \
pip3 install picamera RPi.GPIO 

CMD python LED.py
CMD sensors_to_csv.py
